# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('intro', models.CharField(max_length=256)),
                ('register_by', models.CharField(max_length=64)),
                ('update_at', models.DateTimeField(verbose_name='date updated')),
            ],
        ),
    ]
