# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserinCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=64)),
                ('companyid', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
