# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20171025_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('low', models.IntegerField(default=0)),
                ('high', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=16)),
                ('district', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=32)),
                ('intro', models.CharField(max_length=256)),
                ('update_at', models.DateTimeField(verbose_name='date updated')),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
