# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='register_by',
            field=models.IntegerField(default=0),
        ),
    ]
